version: '3'

services:
  starbound:
    build:
      context: .
      dockerfile: Dockerfile
    image: starbound-server:latest
    ports:
      - "21025:21025"
    volumes:
      - ~/servers/starbound:/starbound/
    env_file:
      - steam.env
    restart: always
