version: '3.7'

services:
  starbound:
    build:
      context: .
      dockerfile: Dockerfile
    image: starbound-server:latest
    ports:
      - "21025:21025"
      - "21026:21026"
    volumes:
      - ./server-data/starbound:/server-data/starbound
    env_file: steam.env
    restart: always
